### ISSUE TITLE
Physical output: student feedback

### ISSUE THREAD

**Issue by amyjko** [amyjko/user-interface-software-and-technology#100]
* What is a ticker machine? It was only mentioned in the chapter as the most ubiquitous before the advent of digital computers. And the image of two women operating the ticker machines and stock exchange boards is not explaining too much.
* Would be great to explain more in details of what are the different types of commercial 3D printers and what are the technologies different from each other. The pros and cons of each type of 3D printers.
* Is laser cutting technology part of this chapter?
* Can IoT be considered as part of physical input? Probably can talk something about IoT.
* Probably can talk about some interesting examples in physical computing.
* Foldable smartphones is coming to the market as fist applications of the foldable interactive objects. Probably can talk about how foldable screen can be applied to other everyday objects.

**Comment by andyjko** [comment]
Though I understand why 3D printing and haptic feedback interfaces are both considered "physical output", they seem fairly disparate. Both seem to be quite rich fields and splitting the chapter between the two limits the space you have to talk about each of them. Does haptic feedback belong more in the section about bodies?

**Comment by andyjko** [comment]
> In the section about morphing, would it be appropriate to introduce the term 4D printing? The heading "morphing" doesn't quite align with the content of the section. As someone who's done a bit of work in 3D modeling programs, morphing has a different connotation and is more directly tied to an action you take within the program as opposed to how the actual 3D object responds to input.

**Comment by andyjko** [comment]
> Bendable/foldable screens are just starting to emerge, and I think would make an interesting addition to the section on morphing. What are the implications of this new technology?

**Comment by andyjko** [comment]
> Since a lot of the videos in this chapter are demos that show different types of technology, it would be nice if those were just gifs, because when it's a video, you have to stop and it kind of interrupts the flow. 

> It would be informative to have a comparison table of the general different types of physical output and what the capabilities and limitations of each are. 

> I felt like the section on morphing should have been part of the chapter on 3D visual output instead.

**Comment by andyjko** [comment]
> When we talk about physical feedback, do we mean only touch and senses? Where will smell fall into?

> I dont know if we should include printing in this chapter. Sure, printing is a physical form, but it's relationship to the digital world is not that clear. Digital is just a way to interact with printing material. Even before the digital world exists, there was printing.  

> Are there any other ways in which the digital world can interact with the physical world in the future? what about IOT devices? Are they considered physical world? Because there is an interface to interact with them.
