### ISSUE TITLE
Intellectual property: student feedback

### ISSUE THREAD

**Issue by amyjko** [amyjko/user-interface-software-and-technology#101]
> Every single source in this chapter is from the same author. I can't imagine that Pamela Samuelson is the only one writing about the intersection between tech and intellectual property–are there more authors you could bring in to give a more diverse take on the subject?

> This could potentially be a good place to talk about how many of today's designers share work openly on websites like Dribbble and Behance, and potentially how that affects uptake in interface ideas in the form of trends/if that introduces new complications to intellectual property.

> Though I know the purpose of much of your writing in this book is to raise questions that we answer for ourselves, I think it would be interesting if you gave your own opinion of IP law in the US in the chapter. You seem to allude to it at the end, where you suggest signing petitions or support new laws–that makes me curious as to what your personal stance is.

**Comment by andyjko** [comment]
> It would have been interesting to read about other more recent patent wars (not just Apple vs Samsung), not necessarily in the chapter but maybe in the additional reading section since the only recent ones available are on Apple and Samsung. 

> The end of the chapter talks about how companies like Facebook and Google warned that forcing Samsung to pay the $399 million in lost profits would lead to an increased number of these cases. However, it doesn't talk about what actually happened or give examples of cases that occurred after as a result. It would've been interesting to see if the number of cases has increased since or to read about examples that happened after. 

> This chapter was very text heavy and lacked the example videos that we normally see in the other chapters, I understand why, since it's a chapter on law and not interfaces that we can provide examples for. But some pictures of the different interfaces being patented for example would have been helpful.

**Comment by andyjko** [comment]
> Typo: “Legal precedent suggested that layouts of content in graphic design are were not copyrightable”. Should eliminate the “are” here.
> Typo: “venture capitalists who invest in ideas are much more interested trade secrets, since they are not public”. Should be “interested in trading”
> Interface design probably can also for in the category of arts/design/architecture, which are also weakly protected by copyright laws in another way. Probably can talk about that?
