### ISSUE TITLE
Tech transfer: student feedback

### ISSUE THREAD

**Issue by amyjko** [amyjko/user-interface-software-and-technology#103]
> Typo: Someone must take an entreprenurial risk. → entrepreneurial
> Would love to learn more about who are the few industry research labs at big companies willing to invest big risks. Like giving examples of the labs.
> How do companies like Apple and Google spot and learn about research ideas? And how could academia speaks up more so the broader public would know that most of the industry concepts came from academic research labs and give them the respect that they deserve? For instance, I didn’t know Siri was inspired by CALO and created by Siri, Inc. before it got acquired by Apple. I always thought Apple internally invented it.
> A photo of the CoMotion was at the top pg this chapter. Would love to learn more about what is CoMotion and how we can use it as our resource at UW to take our design ideas to the next level.

**Comment by andyjko** [comment]
> Probably can elaborate more on your personal experience of founding AnswerDash.
> Probably can talk about one or two successful/non-successful startup examples, which could be founded based on some HCI ideas.
> Talk more about the process of how to get investment with a idea and/or technology.

**Comment by andyjko** [comment]
Typo: “one big five”

**Comment by andyjko** [comment]
entreprenurial risk -> entrepreneurial risk

likely to be any entreprenurs willing -> likely to be any entrepreneurs willing

brain computer interface. - > brain-computer interface

And the public was definitelynot ready for people wandering around - > And the public was definitely not ready for people wandering around

Siri could give them competitive advantage -> Siri could give them a competitive advantage 

created the smartspeaker device category. - > created the smart speaker device category.

 The criteria is pretty clear, even if the strategies for success aren't. ->  The criteria are pretty clear, even if the strategies for success aren't.

 responsibility for high risk ->  responsibility for high-risk

**Comment by andyjko** [comment]
In the section where it is stated that "Someone must take an entreprenurial risk", the word entrepreneurial does not appear correct. VERY HARD TO NOTICE THOUGH!

The text available in this chapter can be broken into smaller sections. For example, What are the implications of these stories for someone in innovating in industry?" is an individual section and making it a different section can facilitate navigation through the text.

I feel like the example of products that were successful or failed can be discussed in detail. Multiple of factors contribute to a success of a product when it comes to finding the right market. In this chapter, we have the opportunity to discuss these factors through examples.

**Comment by andyjko** [comment]
1. This chapter doesn't seem to just apply to interface ideas, but to technology ideas in general. Is there any challenge that is unique to interface idea? For example, it is probably easier to commercialize a product, because there is actual use of a product. However, how to commercialize an interface idea? Even if an interface is good, how to make people adopt that idea?

2. The reading seems to imply that researchers research some sort of idea and test it out first, and then the industry will adopt it. I wonder if this is always the case? For example, the idea of recycling rockets didn't exist before Elon Musk adopts it: he makes it a reality. In this case, a vision exists before the technology exists. 

3. Just wants to say that I have really enjoyed the readings and the class so far.

**Comment by andyjko** [comment]
At what point does something that was once thought of as not feasible become feasible? Even though something is not yet feasible does not stop people from continuing to work on it.
"But if the inventions that researchers like myself create never impact the interfaces we all use every day, what's the point?"… In response to this sentence, it may not impact the interfaces we are currently using but the effects of the research can have impacts many years down the line? Either on new products or eventually change an existing product in an iteration. You mention briefly in a sentence at the end of the chapter.
Are there small ways we can close the gap between research and practice?
