### ISSUE TITLE
Architecture Critiques

### ISSUE THREAD

**Issue by mara-kr** [amyjko/user-interface-software-and-technology#139]
## Nice to haves
- One thing is that it would be nice to add a button image or an infographic of how the state change relationship is like when the mouse clicks the button and when it’s not clicked. 
-  some of the simple drawings in this chapter were hard to read and understand. I love the simple line drawing theme of the book; however, I just think some of these could be made easier to understand.
- Add definition of what high- or low-level implementation
- Consider just using HTML buttons instead of React, either way could use W3Schools/Codepen
- Explanation for code should come before/next to code
- 
## Typos, Small fixes
- Paragraphs are maybe a bit long, could be broken up
- ...program might be in, and the inputs that the can receive that causes it to move between different states.
- ...which does nothing in the code above—is where we might right code to do something…
- ..like the text in a text field or a the current position of a scroll bar?
- whose spatial boundaries contain the mouse.That event.. (space needed)
-  " which is an abstract representation of different states ..., and the inputs that the (they? )can receive that causes it to move between different states. In this state machine, there are two inputs that causes (cause?) changes in states..."
- P2: "A user interface designer or engineer knowing these low-level implementation details is like a violinist knowing..."

- P under button drawing: "Computer scientists call this diagram a state machine, which is an abstract representation of different states that a computer program might be in, and the inputs that the [missing word] can receive that causes it to move between different states."
- Same P: "The button states in this state until it later receives..." should be "stays"?
- P starting w/ "Of course, state machines...": "What about how the widget is presented visually, or how bits of data are stored, like the text in a text field or a the current position of a scroll bar?"
- Same P: "Whatever the storage medium, this is the model." 
- Bulleted list under MVC drawing: "The controller gets and set data in the model when necessary, and tells the view to update itself as the model changes."
- Bulleted list under Component hierarchies, first bullet: "mouse.That event" add a space
- Same P: "...and to it’s parent’s parent,..."
- P under Advances in User Interface Architecture header: "Many of these ideas are now common in modern user interface toolkits, especially the web, in the form of CSS and it’s support for..."
-“Other projects sought to make it easier to “skin” the visual appearance of interfaces without having to modify a user interface implementation” Did you mean SKIM instead of SKIN?
- Also, the link to apple keyboard redesign is not working.

- The sentence under the mouse up and down states diagram that begins with, “Computer scientists call this diagram….”, has an error after “…”and the inputs that the (button) can receive that causes it to move between different states.” I’m not sure, but this seemed grammatically incongruous, “there are two inputs that causes changes…”

**Comment by amyjko** [comment]
Resolved by 5f93ce1
