### ISSUE TITLE
Accessibility Critiques

### ISSUE THREAD

**Issue by mara-kr** [amyjko/user-interface-software-and-technology#140]
## Writing Critiques
- Is it possible to combine paragraph 3 and 4 or shorten it, because it feels like it gets kind of draggy and it takes too long to get into the topic “accessibility”, which is mentioned after 4 paragraphs of introduction.
- Consider adding a paragraph on ethical considerations
- updating the visuals and videos to examples that relate to the most modern technology we use since it would be easier to paint a picture of an example and suggest how accessibility  can be incorporated into interfaces. 
- How can we best serve folx with multiple impairments?
- I think it would be helpful to add in the beginning that most people will experience some form of disability not because of disease or their age, but also temporary disabilities that people suffer for extended periods of time from unanticipated injuries, accidents, or surgeries to really emphasize how important accessibility is in this field. 
- I might add a resource section to this chapter for people interested in learning about how to design a more accessible digital product.

## Typos
- I noticed you repeated the word ‘not’ twice in the 3rd paragraph down
-  ...with the physical world.Optimizing interfaces...(need space)
-  ...by their difficulties, not not sharing their struggles and avoiding access technologies…
-  Other works hows that emoji are a particularly inaccessible form …
- ...and require exceptional ustomization to be useful.
- There is a space missing "...world.Optimizing..." in the second paragraph
- “one billion people (15% of humanity) has some form of disability that impacts their daily activities.” Has should be switched to have. 
-  'alochol' should be alcohol,

**Comment by amyjko** [comment]
Done.
