### ISSUE TITLE
Pointing: typos

### ISSUE THREAD

**Issue by amyjko** [amyjko/user-interface-software-and-technology#85]
1. Correct typos (CMD+F)
Original - In fact, back in the early 1950’s
Updated - In fact, back in the early 1950s
As an mathematical model 
As a mathematical model
2. Suggested example: When talking about absolute and relative pointing, there are now car interfaces such that in the new Acura RDX that have the new interface which utilizes direct pointing (absolute positioning) on a trackpad which is separate from the screen. See article linked. (Links to an external site.)Links to an external site.
3. Original text: "But there are some other interesting implications for user interface design in the algebraic extremes. For example, what if the target size is infinite? An example of this is the command menu in Apple OS X applications, which is always placed at the very top of a screen. "
Suggestion: Another example that can be added is adding the Windows 10 Start button as another example of infinite target size.

**Comment by andyjko** [comment]
> In the middle of paragraph 3, specifically this sentence, “This is an example of a “closed loop” motion, in which a system can react to its evolving state.” the reference is somewhat unclear. The pronoun “this” seems to be referencing the case in the previous sentences but at first read I thought it could have been referencing the equation below. Either way, to remove ambiguity, I suggest replacing “this” with “In this case” or  “in the example below”.

**Comment by andyjko** [comment]
> “ Each has their limitations: direct pointing results in occlusion where a person's hand obscures output, and indirect pointing requires a person to attend to two different places.” Pedantically, I suggest: “ Each has their limitations: direct pointing *can results in occlusion where a person's hand obscures output, and indirect pointing requires a person to attend to two different places.”

**Comment by andyjko** [comment]
> “All of these device manipulations seek to decrease pointing time by increasing throughput and reducing the time to start a motion.” Throughput. Consider using turnout or output. Throughput seems unnecessarily technical and allows room for the reader to hold to the conceptual understanding with less need for translation.
